### ISSUE TITLE
Cannot run the tapas-build command

### ISSUE THREAD

**Issue by karloku** [TapasFE/tapas-build#8]
``` sh
→ tapas-build -i index.html application.js ../public
module.js:341
    throw err;
    ^

Error: Cannot find module '../src/main'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> ($HOME/.nvm/versions/node/v5.10.1/lib/node_modules/tapas-build/bin/tapas-build:21:5)
```

**Comment by karloku** [comment]
``` sh
→ tree $HOME/.nvm/versions/node/v5.10.1/lib/node_modules/tapas-build/ -L 2
$HOME/.nvm/versions/node/v5.10.1/lib/node_modules/tapas-build/
├── HISTORY.md
├── LICENSE
├── README.md
├── bin
│   └── tapas-build
├── build
│   ├── constant
│   ├── devServer.js
│   ├── getConfig.js
│   ├── getDefaultConfig.js
│   ├── main.js
│   └── methods
├── node_modules
│   ├── ...
```

try to tree the module path
